"""empty message

Revision ID: d9dfb514fc67
Revises: 
Create Date: 2025-01-13 03:04:35.698575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9dfb514fc67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('disponibilidad', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('disponibilidad', sa.Boolean(), nullable=True),
    sa.Column('categoriaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoriaId'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cuentas')
    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clientes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('BUEN_CLIENTE', 'CLIENTE_RIESGOSO', 'CLIENTE PELIGROSO', name='status_enum'), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey'),
    sa.UniqueConstraint('correo', name='clientes_correo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cuentas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_cuenta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo_moneda', postgresql.ENUM('SOLES', 'DOLARES', 'EUROS', name='tipo_moneda_enum'), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('mantenimiento', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='fk_clientes'),
    sa.PrimaryKeyConstraint('id', name='cuentas_pkey'),
    sa.UniqueConstraint('numero_cuenta', name='cuentas_numero_cuenta_key')
    )
    op.drop_table('productos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
